import React from 'react';
import serviceImage from './images/service.png'; // Adjust path as per your project structure
import UploadComponent from '../components/TextAnalysis/TextAnalysis';
import s1 from './images/s1.jpeg';
import s2 from './images/s2.jpeg';
import s4 from './images/s4.jpeg';
import s3 from './images/s3.jpeg';
function Services1() {
  return (
    <div>
      <div className="relative" style={{ backgroundColor: 'lightgrey' }}>
        {/* Background Image Section */}
        <div className="relative bg-cover bg-center" style={{ backgroundImage: `url(${serviceImage})`, height: "80vh" }}>
          <div className="absolute inset-0 bg-black opacity-40"></div> {/* Overlay for better text visibility */}
          <div className="max-w-3xl mx-auto px-4 py-8 relative z-10">
            <section className="mb-8">
              <h2 className="text-3xl font-bold mb-4 text-center text-white" style={{ padding: '80px' }}>AI vs. Human Content Analysis</h2>
              <p className="text-lg leading-relaxed text-center text-white">
                Curious about the authorship of your content? Our cutting-edge analysis can determine whether text was generated by AI or written by a human. Through sophisticated linguistic analysis and pattern recognition, we provide reliable insights into the origins of the content.
              </p>
            </section>
          </div>
        </div>


        <div className="max-w-5xl mx-auto px-4 py-8">
          <h2 style={{ width: '100%', textAlign: 'center', marginBottom: '30px', color: '#088178' }}>Why Choose Our Analysis Service?</h2>
          <h2 className="text-2xl font-bold text-center mb-4" style={{ color: '#3bb19b' }}></h2>

          <div className="flex flex-wrap justify-center">

            <div className="w-full md:w-1/2 lg:w-1/3 px-4 mb-4">
              <div className="border rounded-lg p-4 h-full" style={{ backgroundColor: '#3bb19b' }}>
                <h3 className="text-xl font-bold mb-2 text-center text-white">Accurate Authorship Identification</h3>
                <ul className="list-disc ml-4 text-white">
                  <li>Academic Integrity: Students and educators can verify the authenticity of papers and assignments.</li>
                  <li>Content Creation: Writers and publishers can validate the originality of their work.</li>
                  <li>Legal and Compliance: Professionals rely on accurate authorship identification.</li>
                </ul>
              </div>
            </div>


            <div className="w-full md:w-1/2 lg:w-1/3 px-4 mb-4">
              <div className="border rounded-lg p-4 h-full" style={{ backgroundColor: '#3bb19b' }}>
                <h3 className="text-xl font-bold mb-2 text-center text-white">Insights into Content Origins</h3>
                <ul className="list-disc ml-4 text-white">
                  <li>Language Patterns: Detect subtle differences in language usage.</li>
                  <li>Contextual Understanding: Analyze semantic nuances that reveal the origin of the content.</li>
                </ul>
              </div>
            </div>


            <div className="w-full md:w-1/2 lg:w-1/3 px-4 mb-4">
              <div className="border rounded-lg p-4 h-full" style={{ backgroundColor: '#3bb19b' }}>
                <h3 className="text-xl font-bold mb-2 text-center text-white">Enhanced Content Quality Assurance</h3>
                <ul className="list-disc ml-4 text-white">
                  <li>Quality Assurance: Ensure content meets standards of authenticity and relevance.</li>
                  <li>Efficiency: Streamline content review processes.</li>
                  <li>Risk Mitigation: Reduce the risk of unintentional plagiarism.</li>
                </ul>
              </div>
            </div>

            <div className="w-full md:w-1/2 lg:w-1/3 px-4 mb-4">
              <div className="border rounded-lg p-4 h-full" style={{ backgroundColor: '#3bb19b' }}>
                <h3 className="text-xl font-bold mb-2 text-center text-white">Customizable Solutions for Every Need</h3>
                <ul className="list-disc ml-4 text-white">
                  <li>Custom Integrations: Seamlessly integrate our tools into existing platforms.</li>
                  <li>Scalability: Scale our services to meet varying levels of demand.</li>
                  <li>Consultative Support: Receive expert guidance on leveraging our tools effectively.</li>
                </ul>
              </div>
            </div>


            <div className="w-full md:w-1/2 lg:w-1/3 px-4 mb-4">
              <div className="border rounded-lg p-4 h-full" style={{ backgroundColor: '#3bb19b' }}>
                <h3 className="text-xl font-bold mb-2 text-center text-white">Commitment to Excellence</h3>
                <ul className="list-disc ml-4 text-white">
                  <li>Accuracy: Utilize state-of-the-art algorithms for precise identification.</li>
                  <li>Reliability: Dependable results backed by rigorous testing.</li>
                  <li>User-Centric Experience: Enhance user satisfaction with detailed reporting.</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="relative">
        {/* Background Image Section */}
        <div className="relative bg-cover bg-center" style={{ backgroundImage: `url(https://www.softwaretestinghelp.com/wp-content/qa/uploads/2020/04/Top-Plagiarism-Checker-Software.png)`, height: "70vh" }}>
          <div className="absolute inset-0 bg-black" style={{ filter: 'blur(5px)', opacity: '0.6' }}></div> {/* Blurred overlay */}
          <div className="absolute inset-0 bg-black opacity-30"></div> {/* Additional overlay for better text visibility */}
          <div className="relative z-10 max-w-3xl mx-auto px-4 py-8">
            <section className="mb-8">
              <h2 className="text-3xl font-bold mb-4 text-center" style={{ padding: '40px 0', color: 'white' }}>Plagiarism Detection</h2>
              <p className="text-lg leading-relaxed text-center" style={{ color: 'white' }}>
                Ensure originality and integrity of your content with our robust plagiarism detection service. Whether you submit text directly or upload .odf, .docx, or .txt files, our advanced algorithms scan millions of sources to pinpoint similarities and highlight potential instances of plagiarism. Receive detailed reports with percentage matches and source links for thorough review.
              </p>
            </section>
          </div>
        </div>


      </div>
    </div>
  );
}

const Services2 = () => {
  return (
    <div className="container mx-auto p-6">
      <div className="flex flex-wrap mb-10">
        <div className="w-full md:w-2/5 p-4 hover-grow">
          <img src={s1} alt="Detailed Metrics Image" className="w-full h-64 md:h-80 object-cover transform transition-transform duration-300 hover:scale-110" />
        </div>
        <div className="w-full md:w-3/5 p-4">
          <h3 className="text-xl font-bold mb-4">Detailed Metrics</h3>
          <p>Gain comprehensive insights into your text composition:</p>
          <ul className="list-disc ml-6">
            <li>Word Count: Accurately measure the total number of words in your document or input.</li>
            <li>Sentence Count: Analyze the structure and complexity of your text with a breakdown of sentences.</li>
            <li>Paragraph Count: Understand content organization and flow with total paragraph count metrics.</li>
          </ul>
        </div>
      </div>

      <div className="flex flex-wrap mb-10">
        <div className="w-full md:w-3/5 p-4 order-2 md:order-1">
          <h3 className="text-xl font-bold mb-4">Customizable Reporting Options</h3>
          <p>Choose how you want to receive and utilize your analysis results:</p>
          <ul className="list-disc ml-6">
            <li>Downloadable Reports: Easily download detailed reports in PDF or other formats for offline review and reference.</li>
            <li>Email Delivery: Receive comprehensive reports directly in your inbox for immediate access and sharing with stakeholders.</li>
          </ul>
        </div>
        <div className="w-full md:w-2/5 p-4 order-1 md:order-2 hover-grow">
          <img src={s3} alt="Customizable Reporting Options Image" className="w-full h-64 md:h-80 object-cover transform transition-transform duration-300 hover:scale-110" />
        </div>
      </div>

      <div className="flex flex-wrap mb-10">
        <div className="w-full md:w-2/5 p-4 hover-grow">
          <img src={s2} alt="Integration and Flexibility Image" className="w-full h-64 md:h-80 object-cover transform transition-transform duration-300 hover:scale-110" />
        </div>
        <div className="w-full md:w-3/5 p-4">
          <h3 className="text-xl font-bold mb-4">Integration and Flexibility</h3>
          <p>Our services are designed to seamlessly integrate into your workflow:</p>
          <ul className="list-disc ml-6">
            <li>API Integration: Integrate our powerful tools directly into your applications or platforms for automated analysis and reporting.</li>
            <li>Custom Solutions: Tailor our services to meet specific needs or industry requirements, ensuring maximum efficiency and accuracy.</li>
          </ul>
        </div>
      </div>

      <div className="flex flex-wrap mb-10">
        <div className="w-full md:w-3/5 p-4 order-2 md:order-1">
          <h3 className="text-xl font-bold mb-4">Expert Support</h3>
          <p>Receive dedicated support from our team of experts:</p>
          <ul className="list-disc ml-6">
            <li>Technical Assistance: Access assistance with setup, troubleshooting, and optimizing your use of our services.</li>
            <li>Consultative Services: Receive guidance on best practices for content analysis, plagiarism prevention, and data interpretation.</li>
          </ul>
        </div>
        <div className="w-full md:w-2/5 p-4 order-1 md:order-2 hover-grow">
          <img
            src={s4}
            alt="Expert Support Image"
            className="w-full h-64 md:h-80 object-cover transform transition-transform duration-300 hover:scale-110"
          />
        </div>
      </div>
    </div>)
};
function ServicesPage() {
  return (
    <div>
      <Services1 />
      <Services2 />
      <UploadComponent />
    </div>
  );
}



export default ServicesPage;
